### ISSUE TITLE
first exercise

### ISSUE THREAD

**Issue by stevee-bee** [AlanBerger/Practice-programming-exercises-for-R#1]
Hi @AlanBerger,

Thanks for sharing these practice exercises!

Not sure if this a preferred place for feedback or if you would rather they be shared as a response to [your post](https://www.coursera.org/learn/r-programming/discussions/weeks/2/threads/vVM15kIXEeuiiw7DLZfcgw) on Coursera. Please let me know and I can repost there.

Regarding the first programming exercise, I found myself coding the first version of my function to handle the possibility of a vector of column names instead of just a single column. This _is_ eventually where we are going with the exercise, but I don't know if this is worth clarifying/emphasizing that just one column value is passed to the initial function.

Looking back, I see that line 57 does say:

`    # convert an Excel column name`

so perhaps it's my misread, but then I think it was line 83 where I started thinking that the expectation was that it had to accept a vector argument:

`Your function, when applied to b, g, k, q and w (as character variables)`

Regards,
Steve

**Comment by AlanBerger** [comment]
Hello Steve,

Thank you for your comments.  By all means please post them as a reply on the R Programming Course Discussion Forum so others in the class can see them directly there,

Alan


________________________________
